### PR TITLE
Update celery settings and namespace

### PR DESCRIPTION
**Pull request by iamsobanjaved**
## Description

Update celery settings and namespace

## Ticket Link

Link to the associated ticket
[BOM-2037](https://openedx.atlassian.net/browse/BOM-2037)

## Post-review

Squash commits into discrete sets of changes

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
@bbaker6225 this needs verification that celery tasks and workers are working fine. Should we merge this and you verify it from stage?

**Review by bbaker6225 — APPROVED** [review]
Yes, feel free to merge and I'll test it on stage

**Comment by iamsobanjaved** [comment]
@bbaker6225 I have merged this.

**Comment by bbaker6225** [comment]
@iamsobanjaved This worked on stage, I'm deploying to prod now
image

**Comment by iamsobanjaved** [comment]
@bbaker6225 Thanks 👍

**Pull request merged**
