### PR TITLE
chore: upgrade Django to 3.2.20

### PR DESCRIPTION
**Pull request by magajh**
See: https://github.com/openedx/wg-build-test-release/issues/298

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @magajh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @magajh! Looks like there's some failing tests - would you mind taking a look before we get it reviewed? Thanks!

**Comment by mphilbrick211** [comment]
> Hi @magajh! Looks like there's some failing tests - would you mind taking a look before we get it reviewed? Thanks!

Hi @magajh! Just following up on this :)

**Comment by mtyaka** [comment]
@magajh Can you pull in the latest updates from the [open-release/palm.master branch](https://github.com/openedx/enterprise-catalog/tree/open-release/palm.master)?

I think that will fix the issue with the CI.

**Comment by mtyaka** [comment]
@magajh In order to get this merged before Palm.2 release, I opened a [new PR](https://github.com/openedx/enterprise-catalog/pull/663) with your fix. Thank you for your work!

**Comment by openedx-webhooks** [comment]
@magajh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/enterprise-catalog&entry.867055334=https://github.com/openedx/enterprise-catalog/pull/648&entry.1484655318=https://github.com/magajh&entry.752974735=2023-07-13+15:58&entry.1917517419=2023-08-09+07:05&entry.2133058324=No) so we can improve your experience in the future.

**Comment by magajh** [comment]
Thanks a lot for taking the initiative and ensuring this fix made it into the release, @mtyaka. Apologies for not being able to address this sooner. Appreciate your understanding and effort!

**Pull request closed without merging**
