### PR TITLE
feat: make skill_names facet searchable

### PR DESCRIPTION
**Pull request by muhammad-ammar**
## Description

Make `skill_names` facet searchable to be able to search inside it.

## Ticket Link
[ENT-4104](https://openedx.atlassian.net/browse/ENT-4104)

## Post-review

Squash commits into discrete sets of changes

### CODE REVIEW

**Review by adamstankiewicz — APPROVED** [review]

**Comment by muhammad-ammar** [comment]
@adamstankiewicz Thank You! Any idea how much time it will take to reflect changes in `enterprise_catalog_new` index?

**Comment by adamstankiewicz** [comment]
@muhammad-ammar The Algolia indexing happens once per day, so tomorrow morning around ~830am EST unless we run the "reindex_algolia" job in Jenkins.

If you have Algolia admin access, you could also make the change via the Algolia dashboard in the meantime. When the job runs tomorrow morning, the index will be "re-configured" with the same setting with this PR merged.

**Comment by muhammad-ammar** [comment]
> @muhammad-ammar The Algolia indexing happens once per day, so tomorrow morning around ~830am EST unless we run the "reindex_algolia" job in Jenkins.
> 
> If you have Algolia admin access, you could also make the change via the Algolia dashboard in the meantime. When the job runs tomorrow morning, the index will be "re-configured" with the same setting with this PR merged.

@adamstankiewicz I have made the same change via Algolia admin dashboard yesterday but still seeing the below error whenever I try to search inside facets list.

Screenshot 2021-03-08 at 7 14 06 PM

Any concerns if we run the jenkins `reindex_algolia` job now?

**Comment by adamstankiewicz** [comment]
@muhammad-ammar Since the `reindex_algolia` job ran this morning, it overwrote your manual changes from yesterday in the Algolia admin dashboard:

image

I just changed the facet back to be searchable again.

**Comment by muhammad-ammar** [comment]
@adamstankiewicz Thank You!

**Pull request merged**
